In [1]:
#Import dependencies
import pandas as pd
import numpy as np
import glob
import os

### Import & Cleanse Top 20 Data

In [2]:
#  Import and read the Wildfire CSV.
top20_df = pd.read_csv("Resources/top_20_CA_wildfires.csv")
top20_df

,fire_name,cause,month,year,county,acres,structures,deaths
0,Mendocino Complex,Under Investigation,July,2018,"Colusa County, Lake County, Mendocino County &...",459123,280,1
1,Thomas,Powerlines,December,2017,Ventura & Santa Barbara,281893,1063,2
2,Cedar,Human Related,October,2003,San Diego,273246,2820,15
3,Rush,Lightning,August,2012,Lassen,271911,0,0
4,Rim,Human Related,August,2013,Tuolumne,257314,112,0
5,Zaca,Human Related,July,2007,Santa Barbara,240207,1,0
6,Carr,Human Related,July,2018,"Shasta County,Trinity County",229651,1614,8
7,Matilija,Undetermined,September,1932,Ventura,220000,0,0
8,Witch,Powerlines,October,2007,San Diego,197990,1650,2
9,Klamath Theater Complex,Lightning,June,2008,Siskiyou,192038,0,2
10,Marble Cone,Lightning,July,1977,Monterey,177866,0,0
11,Laguna,Powerlines,September,1970,San Diego,175425,382,5
12,Basin Complex,Lightning,June,2008,Monterey,162818,58,0
13,Day Fire,Human Related,September,2006,Ventura,162702,11,0
14,Station,Human Related,August,2009,Los Angeles,160557,209,2
15,Camp Fire,Powerlines,November,2018,Butte,153336,18804,85
16,Rough,Lightning,July,2015,Fresno,151623,4,0
17,Mcnally,Human Related,July,2002,Tulare,150696,17,0
18,Stanislaus Complex,Lightning,August,1987,Tuolumne,145980,28,1
19,Big Bar Complex,Lightning,August,1999,Trinity,140948,0,0

In [3]:
#Data is out of date, replace Mendocino Complex "Under Investigation" with latest information "Human Related"
top20_df.at[0, 'cause'] = "Human Related"
top20_df

,fire_name,cause,month,year,county,acres,structures,deaths
0,Mendocino Complex,Human Related,July,2018,"Colusa County, Lake County, Mendocino County &...",459123,280,1
1,Thomas,Powerlines,December,2017,Ventura & Santa Barbara,281893,1063,2
2,Cedar,Human Related,October,2003,San Diego,273246,2820,15
3,Rush,Lightning,August,2012,Lassen,271911,0,0
4,Rim,Human Related,August,2013,Tuolumne,257314,112,0
5,Zaca,Human Related,July,2007,Santa Barbara,240207,1,0
6,Carr,Human Related,July,2018,"Shasta County,Trinity County",229651,1614,8
7,Matilija,Undetermined,September,1932,Ventura,220000,0,0
8,Witch,Powerlines,October,2007,San Diego,197990,1650,2
9,Klamath Theater Complex,Lightning,June,2008,Siskiyou,192038,0,2
10,Marble Cone,Lightning,July,1977,Monterey,177866,0,0
11,Laguna,Powerlines,September,1970,San Diego,175425,382,5
12,Basin Complex,Lightning,June,2008,Monterey,162818,58,0
13,Day Fire,Human Related,September,2006,Ventura,162702,11,0
14,Station,Human Related,August,2009,Los Angeles,160557,209,2
15,Camp Fire,Powerlines,November,2018,Butte,153336,18804,85
16,Rough,Lightning,July,2015,Fresno,151623,4,0
17,Mcnally,Human Related,July,2002,Tulare,150696,17,0
18,Stanislaus Complex,Lightning,August,1987,Tuolumne,145980,28,1
19,Big Bar Complex,Lightning,August,1999,Trinity,140948,0,0

In [4]:
cause = top20_df.groupby('cause')['acres'].sum()
cause

cause
Human Related    1933496
Lightning        1243184
Powerlines        808644
Undetermined      220000
Name: acres, dtype: int64

In [8]:
year = top20_df[top20_df.year > 2012]
year

,fire_name,cause,month,year,county,acres,structures,deaths
0,Mendocino Complex,Human Related,July,2018,"Colusa County, Lake County, Mendocino County &...",459123,280,1
1,Thomas,Powerlines,December,2017,Ventura & Santa Barbara,281893,1063,2
4,Rim,Human Related,August,2013,Tuolumne,257314,112,0
6,Carr,Human Related,July,2018,"Shasta County,Trinity County",229651,1614,8
15,Camp Fire,Powerlines,November,2018,Butte,153336,18804,85
16,Rough,Lightning,July,2015,Fresno,151623,4,0

### Export CSV

In [9]:
year.to_csv("Resources/top_fire_clean.csv")